name: real_to_do_list
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.11.2
  flutterfire_cli: ^0.2.4
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # core utilities
  kartal: ^2.1.0
  logger: ^1.0.0
  webview_flutter: ^2.0.4
  # state management
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^5.0.0
  # ui utilities
  animations: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0-nullsafety
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  lottie: ^1.0.1
  shimmer: ^2.0.0-nullsafety.0


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:

    - asset/svg/

  